### ISSUE TITLE
Can't enable the script "Export Objective-C Header (.h)"

### ISSUE THREAD

**Issue by Calcimicium** [jlamarche/iOS-OpenGLES-Stuff#8]
Hello !

I work with an iMac running on MAC OS 10.6.8 and the version 2.57 of Blender.
 I perfectly installed the script but I can't enable it...

On the console window, I have the following message :

Traceback (most recent call last):
  File "/Applications/Blender/blender.app/Contents/MacOS/2.57/scripts/modules/addon_utils.py", line 207, in enable
    mod = **import**(module_name)
  File "/Applications/Blender/blender.app/Contents/MacOS/2.57/scripts/addons/io_export_objective_c_header.py", line 26, in <module>
    import bpy_extras
ImportError: No module named bpy_extras

Thank you very much

Frenchy Calcimicium

**Comment by jlamarche** [comment]
Update to a newer version of Blender. The current version is 2.63a. There was a change to the API around 2.59 IIRC that changed the namespace of bpy_extras.
